"""record reservation resolution time

Revision ID: 4d485769f601
Revises: 5cf1fa398b98
Create Date: 2026-09-28 18:35:58.787518
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "4d485769f601"
down_revision = "5cf1fa398b98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "risk_reservations", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_reservations", "resolved_at")
    # ### end Alembic commands ###
